FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

COPY wait_for_keycloak1.sh /app/wait_for_keycloak.sh

RUN chmod +x /app/wait_for_keycloak1.sh

CMD ["/app/wait_for_keycloak1.sh"]